### ISSUE TITLE
Fails after upgrading to 2022.7.0

### ISSUE THREAD

**Issue by thomas70** [atxbyea/samsungrac#46]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Klima (documentation, issues)
First occurred: 00:58:33 (2 occurrences)
Last logged: 00:58:33

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode

**Comment by hoeselr** [comment]
same issue on our side

**Comment by giig982** [comment]
it's a duplicate of #44

**Comment by atxbyea** [comment]
Should be fixed in 4.1 thanks to @CookingBlight !

**Comment by benshemmeld** [comment]
After updating to 4.1 I'm still getting this error for samsung_2878

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 9:23:40 PM (2 occurrences)
Last logged: 9:23:40 PM

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode
```

Here's my config:
```
- platform: climate_ip
  name: 'Air Conditioner'
  config_file: 'samsung_2878.yaml'
  ip_address: '[ip_address]'
  token: '[token]'
  cert: ''
  mac: '[mac address]'
  poll: True
```

**Comment by atxbyea** [comment]
I think I found a fix here, but I have to wait until I don't have a sleeping baby on top of me up implement a fix
https://github.com/home-assistant/core/pull/71443/files

**Comment by walkerleigh** [comment]
Hey @atxbyea and @CookingBlight thanks for the swift response on this. I still have the issue too but no rush, sleeping babies etc. come first. :)

**Comment by atxbyea** [comment]
Yes, to me it looks like the entire component needs rewriting to move away from the deprecated stuff in HA.... I've been playing around, and gotten it to load, but I can't read any values nor write any values to my 2878 based device....
My profiency in python is not very good, but I've kept this component alive for a while after sabuzet vanished... hopefully someone who is more proficient in python knows how to rewrite it to work in post 2022.05 HA..

I've been trying to follow the MELCLOUD one tonight to no avail, because I'm just not proficient enough to make it work with the existing framework of this integration

https://github.com/ollo69/ha-melcloud-custom/blob/master/custom_components/melcloud_custom/climate.py

**Comment by benshemmeld** [comment]
@atxbyea thanks for your work on this issue. Not sure if it helps, but for me it only failed to load after installing HA 2022.7.  I've now (temporarily) rolled back to 2022.6.7 and it's working again.

**Comment by atxbyea** [comment]
I've always wanted a good reason to actually learn python, perhaps now is the time, but I can guarantee no timeframe.

**Comment by CookingBlight** [comment]
I have been looking at the code a bit, and I don't think this issue is caused by the deprecated constants as I don't believe they are actually used. I still think it is caused by an ssl error as I got the exact same errors while debugging the problems on my installation. It seems like a failure to connect to the unit also fails to set the mode. Because no error logging is done while establishing the connection, the first error to show up is for the incorrect mode.

I seem to remember that the new ssl libararies refused to work without a certificate. The configuration further up seem to have a configuration without a certificate, which as far as I can remember would cause the ssl connection to fail. Without the full debug log turned on this error won't show up. The extra logging I added in my fork only had this logged as information, so the error won't show up unless debugging is turned on and the full log is posted.

To better help debug this problem I will try to add some better error checking and logging to my fork.

I have a bit much on my plate at the moment, so this might take a while. I'm also much more profficient in C style languages so please excuse any weirdness in my code. There is also a good chance that I'm entirely wrong and this is caused by something else entirely.

Regardsless! Thank you @atxbyea for keeping this component going. It is much appreciated!

**Comment by dapuzz** [comment]
Try to replace sslContext.set_ciphers("HIGH:!DH:!aNULL") on line 248 in samsung_2878.py with sslContext.set_ciphers("ALL:@SECLEVEL=0")

This worked for me!

**Comment by Jens-Wymeersch** [comment]
@dapuzz Thank you for your comment. Would it be possible to indicate which version you have of HA ?

**Comment by thomas70** [comment]
> Try to replace sslContext.set_ciphers("HIGH:!DH:!aNULL") on line 248 in samsung_2878.py with sslContext.set_ciphers("ALL:@SECLEVEL=0")
> 
> [#44 (comment)](https://github.com/atxbyea/samsungrac/issues/44#issuecomment-1177394938)
> 
> This worked for me!

Thank you. Worked for me to :-) 2022.7.4

**Comment by benshemmeld** [comment]
Thanks @dapuzz! That worked for me too. I really appreciate the fix.

**Comment by Jens-Wymeersch** [comment]
Thanks @dapuzz! That worked for me too. @atxbyea Would it be possible to add it to the new build for HACS ?

**Comment by CookingBlight** [comment]
I have created a pull request. I have also added some error logging to help with any new issues reported about the same problem.

As mentioned in issue #40 this might break the component for some units, but I can't figure out how that could be as "ALL:@SECLEVEL=0" basically allows anything. At the moment it seems as if the libraries used in the newest and previous version of python/openssl handles this differently and in some cases it causes problems.

It might also be a good idea to add some error checking on the socket wrapper in samsung_2878.py as well. I don't have one of these units so I can't really do much work on that part of the code.

**Comment by atxbyea** [comment]
Merged, thanks @CookingBlight I'll see if this fixes the issue on my end too as I have a 2878 unit.

**Comment by walkerleigh** [comment]
Mine works again now. Thanks again all involved.

**Comment by giig982** [comment]
I just updated to HA 2022.7.5 and Climate Ip 4.2 and again I cannot connect to my 2278 units.

My configuration is:
```
climate:
  - platform: climate_ip
    name: AC Cucina
    config_file: "/config/custom_components/climate_ip/samsung_2878.yaml"
    ip_address: REDACTED
    mac: REDACTED
    token: !secret climaCucinaTk
    cert: "ac14k_m.pem" 
    poll: true
    debug: True

  - platform: climate_ip
    name: AC CameraLetto
    config_file: "/config/custom_components/climate_ip/samsung_2878.yaml"
    ip_address: REDACTED
    mac: REDACTED
    token: !secret climaCameralettoTk
    cert: ""  #set as '' to skip certificate verification
    poll: true
    debug: True
```

Connection fails with the following error for the unit without cert:

```
2022-07-18 12:44:00 INFO (SyncWorker_4) [custom_components.climate_ip.climate] Traceback (most recent call last):
  File "/config/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command
    sslSocket = self.socket
  File "/config/custom_components/climate_ip/samsung_2878.py", line 281, in socket
    self.create_connection()
  File "/config/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection
    sslSocket.connect((cfg.host, cfg.port))
  File "/usr/local/lib/python3.10/ssl.py", line 1375, in connect
    self._real_connect(addr, False)
  File "/usr/local/lib/python3.10/ssl.py", line 1366, in _real_connect
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)
```


And the following error for unit with cert:

```
2022-07-18 12:43:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 762, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode
```

So, as I said in issue #40 that ciphers configuration might break the component for some unit (mine), so tried to modify line [248](https://github.com/atxbyea/samsungrac/blob/master/custom_components/climate_ip/samsung_2878.py#L248)
again from this, 

        `sslContext.set_ciphers("ALL:@SECLEVEL=0")`
to this:

        # sslContext.set_ciphers("ALL:@SECLEVEL=0")
        sslContext.set_ciphers('DEFAULT@SECLEVEL=0')
        sslContext.set_ciphers("HIGH:!DH:!aNULL")

AND, following https://stackoverflow.com/a/32651967, I also added RC4-SHA to DEFAULT_SSL_CIPHER_LIST  at the top of the file:

```
import requests

requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += ':RC4-SHA'
try:
    requests.packages.urllib3.contrib.pyopenssl.DEFAULT_SSL_CIPHER_LIST += ':RC4-SHA'
except AttributeError:
    # no pyopenssl support used / needed / available
    pass

CONNECTION_TYPE_S2878 = "samsung_2878"
```

@atxbyea and @CookingBlight  this is the only way I know at the moment to have my 2278 units work. I'm not able to say if there could be a configuration switch that can include that kind of configuration nor if there's someone else that have this problem.

**Comment by Zizio82** [comment]
> 

I have the same problem and i edited only this:

    # sslContext.set_ciphers("ALL:@SECLEVEL=0")
    sslContext.set_ciphers('DEFAULT@SECLEVEL=0')
    sslContext.set_ciphers("HIGH:!DH:!aNULL")

on samsung_2878.py. Now is ok with HA 2022.8.6 and 4.2 version of samsungrac from HACS.

**Comment by nekman** [comment]
HA 2022.9.5 and v4.2 from HACS. Started to work when I changed to not use any cert (`cert: ''`) with the changes from @Zizio82.
